

version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: p
      POSTGRES_DB: data
    # ports:
      # - "1111:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d data"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6543:8081"
    environment:
      DATABASE_URL: "postgres://dbuser:p@db:5432/data"
      DATABASE_CONNECT_TIMEOUT: "30"
      SQLX_OFFLINE: "true"
      FRONTEND_DIST: "./frontend/dist"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # python:
  #   build:
  #     context: ./fastapi-template
  #   depends_on:
  #     - app
  #   healthcheck:
  #     test: ["CMD", "wget", "--spider", "http://localhost:8003/health"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 30s
  #
volumes:
  postgres_data:
  minio_data:

